### ISSUE TITLE
No ForeignKeys in Models

### ISSUE THREAD

**Issue by flesser** [kriberg/armada-sde#3]
First of all: Thanks for your great EVE-related Python/Django resources! :+1: 

While exploring armada-sde, I found that the models included do not have any ForeignKeys, thus it is not possible to browse relations like
```python
jita = MapSolarSystem.objects.get(solar_system_name='Jita')
the_forge = jita.region
```
instead you have to use something like
```python
the_forge = MapRegion.objects.get(pk=jita.region_id)
```

I noticed that `pg_generate_models` has a method named [`generate_foreign_keys`](https://github.com/kriberg/armada-sde/blob/316d5c0a9e9bcbc8e9d3b022700bddd7f0b6272f/armada_sde/management/commands/pg_generate_models.py#L46) as well as [some code](https://github.com/kriberg/armada-sde/blob/316d5c0a9e9bcbc8e9d3b022700bddd7f0b6272f/armada_sde/management/commands/pg_generate_models.py#L179) to handle relations, but it does not seem to work.

What (besides from manually editing the generated models.py) would be the best approach to include that functionality? Is that kind of relation information even included in the PostgreSQL dumps, or would the script have to do some guesswork based on column names ending on `<other_table>_id`?

**Comment by kriberg** [comment]
Fuzzysteve's dump doesn't have foreign keys in it, sadly. So the plan is to try to add them while generating the models. The is_relation is from the original Django inspect source, while the generate_foreign_keys is the start of doing the guess work. The plan is to take the primary key of tables and put it in a dict. Then try some guesswork during inspection. I'll take a crack at it this weekend.

**Comment by kriberg** [comment]
Added support for foreign keys now. There's some voodoo and some overrides, but it works for most tables. Some tables, especially the industry tables, it's not possible to generate working foreign keys, as it requires mapping to composite keys. Need to add custom functions for those, at some point.

**Comment by flesser** [comment]
Wow, great work! Thanks!
